[package]
name = "golem-granary"
version = "0.1.0"
authors = ["maaktweluit <10008353+maaktweluit@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
env_logger = "0.6"
log = "0.4"
